/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SanityRouteImport } from './routes/sanity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as DebugSimpleRouteImport } from './routes/debug-simple'
import { Route as DebugDbRouteImport } from './routes/debug-db'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesIdRouteImport } from './routes/profiles.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as ApiTournamentsRouteImport } from './routes/api/tournaments'
import { Route as ApiThesesRouteImport } from './routes/api/theses'
import { Route as ApiContributorsRouteImport } from './routes/api/contributors'
import { Route as ProfilesIdTradesRouteImport } from './routes/profiles.$id.trades'
import { Route as ProfilesIdPerformanceRouteImport } from './routes/profiles.$id.performance'
import { Route as ApiUsersUpdateNameRouteImport } from './routes/api/users/update-name'
import { Route as ApiProfilesIdRouteImport } from './routes/api/profiles/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProfilesIdTradeHistoryRouteImport } from './routes/api/profiles/$id/trade-history'
import { Route as ApiProfilesIdPerformanceRouteImport } from './routes/api/profiles/$id/performance'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SanityRoute = SanityRouteImport.update({
  id: '/sanity',
  path: '/sanity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSimpleRoute = DebugSimpleRouteImport.update({
  id: '/debug-simple',
  path: '/debug-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugDbRoute = DebugDbRouteImport.update({
  id: '/debug-db',
  path: '/debug-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentsRoute = ApiTournamentsRouteImport.update({
  id: '/api/tournaments',
  path: '/api/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThesesRoute = ApiThesesRouteImport.update({
  id: '/api/theses',
  path: '/api/theses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContributorsRoute = ApiContributorsRouteImport.update({
  id: '/api/contributors',
  path: '/api/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdTradesRoute = ProfilesIdTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => ProfilesIdRoute,
} as any)
const ProfilesIdPerformanceRoute = ProfilesIdPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ProfilesIdRoute,
} as any)
const ApiUsersUpdateNameRoute = ApiUsersUpdateNameRouteImport.update({
  id: '/api/users/update-name',
  path: '/api/users/update-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesIdRoute = ApiProfilesIdRouteImport.update({
  id: '/api/profiles/$id',
  path: '/api/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesIdTradeHistoryRoute =
  ApiProfilesIdTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => ApiProfilesIdRoute,
  } as any)
const ApiProfilesIdPerformanceRoute =
  ApiProfilesIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => ApiProfilesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contributors': typeof ContributorsRoute
  '/debug-db': typeof DebugDbRoute
  '/debug-simple': typeof DebugSimpleRoute
  '/funds': typeof FundsRoute
  '/login': typeof LoginRoute
  '/sanity': typeof SanityRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/posts/$id': typeof PostsIdRoute
  '/profiles/$id': typeof ProfilesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$id': typeof ApiProfilesIdRouteWithChildren
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
  '/profiles/$id/performance': typeof ProfilesIdPerformanceRoute
  '/profiles/$id/trades': typeof ProfilesIdTradesRoute
  '/api/profiles/$id/performance': typeof ApiProfilesIdPerformanceRoute
  '/api/profiles/$id/trade-history': typeof ApiProfilesIdTradeHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contributors': typeof ContributorsRoute
  '/debug-db': typeof DebugDbRoute
  '/debug-simple': typeof DebugSimpleRoute
  '/funds': typeof FundsRoute
  '/login': typeof LoginRoute
  '/sanity': typeof SanityRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/posts/$id': typeof PostsIdRoute
  '/profiles/$id': typeof ProfilesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$id': typeof ApiProfilesIdRouteWithChildren
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
  '/profiles/$id/performance': typeof ProfilesIdPerformanceRoute
  '/profiles/$id/trades': typeof ProfilesIdTradesRoute
  '/api/profiles/$id/performance': typeof ApiProfilesIdPerformanceRoute
  '/api/profiles/$id/trade-history': typeof ApiProfilesIdTradeHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contributors': typeof ContributorsRoute
  '/debug-db': typeof DebugDbRoute
  '/debug-simple': typeof DebugSimpleRoute
  '/funds': typeof FundsRoute
  '/login': typeof LoginRoute
  '/sanity': typeof SanityRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/posts/$id': typeof PostsIdRoute
  '/profiles/$id': typeof ProfilesIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$id': typeof ApiProfilesIdRouteWithChildren
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
  '/profiles/$id/performance': typeof ProfilesIdPerformanceRoute
  '/profiles/$id/trades': typeof ProfilesIdTradesRoute
  '/api/profiles/$id/performance': typeof ApiProfilesIdPerformanceRoute
  '/api/profiles/$id/trade-history': typeof ApiProfilesIdTradeHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contributors'
    | '/debug-db'
    | '/debug-simple'
    | '/funds'
    | '/login'
    | '/sanity'
    | '/signup'
    | '/tournaments'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/posts/$id'
    | '/profiles/$id'
    | '/api/auth/$'
    | '/api/profiles/$id'
    | '/api/users/update-name'
    | '/profiles/$id/performance'
    | '/profiles/$id/trades'
    | '/api/profiles/$id/performance'
    | '/api/profiles/$id/trade-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contributors'
    | '/debug-db'
    | '/debug-simple'
    | '/funds'
    | '/login'
    | '/sanity'
    | '/signup'
    | '/tournaments'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/posts/$id'
    | '/profiles/$id'
    | '/api/auth/$'
    | '/api/profiles/$id'
    | '/api/users/update-name'
    | '/profiles/$id/performance'
    | '/profiles/$id/trades'
    | '/api/profiles/$id/performance'
    | '/api/profiles/$id/trade-history'
  id:
    | '__root__'
    | '/'
    | '/contributors'
    | '/debug-db'
    | '/debug-simple'
    | '/funds'
    | '/login'
    | '/sanity'
    | '/signup'
    | '/tournaments'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/posts/$id'
    | '/profiles/$id'
    | '/api/auth/$'
    | '/api/profiles/$id'
    | '/api/users/update-name'
    | '/profiles/$id/performance'
    | '/profiles/$id/trades'
    | '/api/profiles/$id/performance'
    | '/api/profiles/$id/trade-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributorsRoute: typeof ContributorsRoute
  DebugDbRoute: typeof DebugDbRoute
  DebugSimpleRoute: typeof DebugSimpleRoute
  FundsRoute: typeof FundsRoute
  LoginRoute: typeof LoginRoute
  SanityRoute: typeof SanityRoute
  SignupRoute: typeof SignupRoute
  TournamentsRoute: typeof TournamentsRoute
  ApiContributorsRoute: typeof ApiContributorsRoute
  ApiThesesRoute: typeof ApiThesesRoute
  ApiTournamentsRoute: typeof ApiTournamentsRoute
  PostsIdRoute: typeof PostsIdRoute
  ProfilesIdRoute: typeof ProfilesIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProfilesIdRoute: typeof ApiProfilesIdRouteWithChildren
  ApiUsersUpdateNameRoute: typeof ApiUsersUpdateNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanity': {
      id: '/sanity'
      path: '/sanity'
      fullPath: '/sanity'
      preLoaderRoute: typeof SanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-simple': {
      id: '/debug-simple'
      path: '/debug-simple'
      fullPath: '/debug-simple'
      preLoaderRoute: typeof DebugSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-db': {
      id: '/debug-db'
      path: '/debug-db'
      fullPath: '/debug-db'
      preLoaderRoute: typeof DebugDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournaments': {
      id: '/api/tournaments'
      path: '/api/tournaments'
      fullPath: '/api/tournaments'
      preLoaderRoute: typeof ApiTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/theses': {
      id: '/api/theses'
      path: '/api/theses'
      fullPath: '/api/theses'
      preLoaderRoute: typeof ApiThesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contributors': {
      id: '/api/contributors'
      path: '/api/contributors'
      fullPath: '/api/contributors'
      preLoaderRoute: typeof ApiContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id/trades': {
      id: '/profiles/$id/trades'
      path: '/trades'
      fullPath: '/profiles/$id/trades'
      preLoaderRoute: typeof ProfilesIdTradesRouteImport
      parentRoute: typeof ProfilesIdRoute
    }
    '/profiles/$id/performance': {
      id: '/profiles/$id/performance'
      path: '/performance'
      fullPath: '/profiles/$id/performance'
      preLoaderRoute: typeof ProfilesIdPerformanceRouteImport
      parentRoute: typeof ProfilesIdRoute
    }
    '/api/users/update-name': {
      id: '/api/users/update-name'
      path: '/api/users/update-name'
      fullPath: '/api/users/update-name'
      preLoaderRoute: typeof ApiUsersUpdateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/$id': {
      id: '/api/profiles/$id'
      path: '/api/profiles/$id'
      fullPath: '/api/profiles/$id'
      preLoaderRoute: typeof ApiProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/$id/trade-history': {
      id: '/api/profiles/$id/trade-history'
      path: '/trade-history'
      fullPath: '/api/profiles/$id/trade-history'
      preLoaderRoute: typeof ApiProfilesIdTradeHistoryRouteImport
      parentRoute: typeof ApiProfilesIdRoute
    }
    '/api/profiles/$id/performance': {
      id: '/api/profiles/$id/performance'
      path: '/performance'
      fullPath: '/api/profiles/$id/performance'
      preLoaderRoute: typeof ApiProfilesIdPerformanceRouteImport
      parentRoute: typeof ApiProfilesIdRoute
    }
  }
}

interface ProfilesIdRouteChildren {
  ProfilesIdPerformanceRoute: typeof ProfilesIdPerformanceRoute
  ProfilesIdTradesRoute: typeof ProfilesIdTradesRoute
}

const ProfilesIdRouteChildren: ProfilesIdRouteChildren = {
  ProfilesIdPerformanceRoute: ProfilesIdPerformanceRoute,
  ProfilesIdTradesRoute: ProfilesIdTradesRoute,
}

const ProfilesIdRouteWithChildren = ProfilesIdRoute._addFileChildren(
  ProfilesIdRouteChildren,
)

interface ApiProfilesIdRouteChildren {
  ApiProfilesIdPerformanceRoute: typeof ApiProfilesIdPerformanceRoute
  ApiProfilesIdTradeHistoryRoute: typeof ApiProfilesIdTradeHistoryRoute
}

const ApiProfilesIdRouteChildren: ApiProfilesIdRouteChildren = {
  ApiProfilesIdPerformanceRoute: ApiProfilesIdPerformanceRoute,
  ApiProfilesIdTradeHistoryRoute: ApiProfilesIdTradeHistoryRoute,
}

const ApiProfilesIdRouteWithChildren = ApiProfilesIdRoute._addFileChildren(
  ApiProfilesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributorsRoute: ContributorsRoute,
  DebugDbRoute: DebugDbRoute,
  DebugSimpleRoute: DebugSimpleRoute,
  FundsRoute: FundsRoute,
  LoginRoute: LoginRoute,
  SanityRoute: SanityRoute,
  SignupRoute: SignupRoute,
  TournamentsRoute: TournamentsRoute,
  ApiContributorsRoute: ApiContributorsRoute,
  ApiThesesRoute: ApiThesesRoute,
  ApiTournamentsRoute: ApiTournamentsRoute,
  PostsIdRoute: PostsIdRoute,
  ProfilesIdRoute: ProfilesIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProfilesIdRoute: ApiProfilesIdRouteWithChildren,
  ApiUsersUpdateNameRoute: ApiUsersUpdateNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
