/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as ApiTournamentsRouteImport } from './routes/api/tournaments'
import { Route as ApiThesesRouteImport } from './routes/api/theses'
import { Route as ApiContributorsRouteImport } from './routes/api/contributors'
import { Route as ApiUsersUpdateNameRouteImport } from './routes/api/users/update-name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentsRoute = ApiTournamentsRouteImport.update({
  id: '/api/tournaments',
  path: '/api/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThesesRoute = ApiThesesRouteImport.update({
  id: '/api/theses',
  path: '/api/theses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContributorsRoute = ApiContributorsRouteImport.update({
  id: '/api/contributors',
  path: '/api/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUpdateNameRoute = ApiUsersUpdateNameRouteImport.update({
  id: '/api/users/update-name',
  path: '/api/users/update-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/posts/$id': typeof PostsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/tournaments'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/posts/$id'
    | '/api/auth/$'
    | '/api/users/update-name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/tournaments'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/posts/$id'
    | '/api/auth/$'
    | '/api/users/update-name'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/tournaments'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/posts/$id'
    | '/api/auth/$'
    | '/api/users/update-name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TournamentsRoute: typeof TournamentsRoute
  ApiContributorsRoute: typeof ApiContributorsRoute
  ApiThesesRoute: typeof ApiThesesRoute
  ApiTournamentsRoute: typeof ApiTournamentsRoute
  PostsIdRoute: typeof PostsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUsersUpdateNameRoute: typeof ApiUsersUpdateNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournaments': {
      id: '/api/tournaments'
      path: '/api/tournaments'
      fullPath: '/api/tournaments'
      preLoaderRoute: typeof ApiTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/theses': {
      id: '/api/theses'
      path: '/api/theses'
      fullPath: '/api/theses'
      preLoaderRoute: typeof ApiThesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contributors': {
      id: '/api/contributors'
      path: '/api/contributors'
      fullPath: '/api/contributors'
      preLoaderRoute: typeof ApiContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/update-name': {
      id: '/api/users/update-name'
      path: '/api/users/update-name'
      fullPath: '/api/users/update-name'
      preLoaderRoute: typeof ApiUsersUpdateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TournamentsRoute: TournamentsRoute,
  ApiContributorsRoute: ApiContributorsRoute,
  ApiThesesRoute: ApiThesesRoute,
  ApiTournamentsRoute: ApiTournamentsRoute,
  PostsIdRoute: PostsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUsersUpdateNameRoute: ApiUsersUpdateNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
